# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a46e7cdd930a712efd1ec00efead61f9"
name = "sw-design-hub"
handle = "sw-design-hub"
application_url = "https://marketing-w-negotiations-disks.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://marketing-w-negotiations-disks.trycloudflare.com/auth/callback", "https://marketing-w-negotiations-disks.trycloudflare.com/auth/shopify/callback", "https://marketing-w-negotiations-disks.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
